const TILE_SIZE = 32
const TILE_SPACING = 1
const CELL_SCALE = 2
const TILE_SIZE_SPACED = (TILE_SIZE + TILE_SPACING) * CELL_SCALE
const BATTLEFIELD_COLS = 9
const BATTLEFIELD_ROWS = 9

export { TILE_SIZE, TILE_SPACING, CELL_SCALE, TILE_SIZE_SPACED, BATTLEFIELD_COLS, BATTLEFIELD_ROWS }
